-- MySQL Script generated by MySQL Workbench
-- Tue Dec  9 11:04:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema railway
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema railway
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `railway` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `railway` ;

-- -----------------------------------------------------
-- Table `railway`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCargo`),
  UNIQUE INDEX `nome` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Categorias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `parent_id` BIGINT NULL DEFAULT NULL,
  `prioridade_padrao` ENUM('Planejado', 'BAIXA', 'MEDIA', 'ALTA', 'URGENTE') NULL DEFAULT 'BAIXA',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome` (`nome` ASC) VISIBLE,
  INDEX `fk_categoria_pai` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_pai`
    FOREIGN KEY (`parent_id`)
    REFERENCES `railway`.`Categorias` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomeFuncionario` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `cargoId` INT NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `categoria_id_atendimento` INT NULL DEFAULT NULL,
  `perfil` ENUM('REQUISITANTE', 'AGENTE', 'ADMIN') NOT NULL DEFAULT 'REQUISITANTE',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `usuario` (`usuario` ASC) VISIBLE,
  INDEX `fk_Funcionario_Cargo` (`cargoId` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_Cargo`
    FOREIGN KEY (`cargoId`)
    REFERENCES `railway`.`Cargo` (`idCargo`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Loja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Chamados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Chamados` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `prioridade` VARCHAR(50) NOT NULL DEFAULT 'Média',
  `assunto` VARCHAR(255) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `requisitante_id` INT NOT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'Aberto',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `nome_requisitante_manual` VARCHAR(255) NULL DEFAULT NULL,
  `email_requisitante_manual` VARCHAR(255) NULL DEFAULT NULL,
  `telefone_requisitante_manual` VARCHAR(50) NULL DEFAULT NULL,
  `atendente_id` INT NULL DEFAULT NULL,
  `categoria_unificada_id` BIGINT NULL DEFAULT NULL,
  `loja` VARCHAR(100) NULL DEFAULT NULL,
  `departamento` VARCHAR(100) NULL DEFAULT NULL,
  `loja_id` INT NULL DEFAULT NULL,
  `departamento_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Chamados_Funcionario` (`requisitante_id` ASC) VISIBLE,
  INDEX `fk_chamado_atendente` (`atendente_id` ASC) VISIBLE,
  INDEX `fk_chamado_categoria_unificada` (`categoria_unificada_id` ASC) VISIBLE,
  INDEX `fk_Chamados_Loja` (`loja_id` ASC) VISIBLE,
  INDEX `fk_Chamados_Departamento` (`departamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_chamado_atendente`
    FOREIGN KEY (`atendente_id`)
    REFERENCES `railway`.`Funcionario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_chamado_categoria_unificada`
    FOREIGN KEY (`categoria_unificada_id`)
    REFERENCES `railway`.`Categorias` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_Chamados_Departamento`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `railway`.`Departamento` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Chamados_Funcionario`
    FOREIGN KEY (`requisitante_id`)
    REFERENCES `railway`.`Funcionario` (`id`),
  CONSTRAINT `fk_Chamados_Loja`
    FOREIGN KEY (`loja_id`)
    REFERENCES `railway`.`Loja` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `texto` TEXT NOT NULL,
  `chamado_id` BIGINT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `chamado_id` (`chamado_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `Comentarios_ibfk_1`
    FOREIGN KEY (`chamado_id`)
    REFERENCES `railway`.`Chamados` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `Comentarios_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `railway`.`Funcionario` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`historico_contatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`historico_contatos` (
  `telefone` VARCHAR(50) NOT NULL,
  `nome_perfil` VARCHAR(255) NULL DEFAULT NULL,
  `url_foto` TEXT NULL DEFAULT NULL,
  `ultima_interacao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`telefone`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`loja_departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`loja_departamento` (
  `loja_id` INT NOT NULL,
  `departamento_id` INT NOT NULL,
  PRIMARY KEY (`loja_id`, `departamento_id`),
  INDEX `departamento_id` (`departamento_id` ASC) VISIBLE,
  CONSTRAINT `loja_departamento_ibfk_1`
    FOREIGN KEY (`loja_id`)
    REFERENCES `railway`.`Loja` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `loja_departamento_ibfk_2`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `railway`.`Departamento` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
